#!/bin/bash
# Erzeugt ein ZIP‑Paket der bereits cross‑gebauten Win64‑Binaries (ohne PDB / Debug-Infos).
#
# Usage:
#  ./make-windows-package.sh [SRC_DIR] [VERSION]
#
# Wenn SRC_DIR fehlt, wird der Parent des Skriptverzeichnisses verwendet.
# Das erzeugte Paket landet in build/win64/packages/

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [[ -n "${1-}" ]]; then
  SRC_DIR="$1"
else
  SRC_DIR="$(readlink -f "$SCRIPT_DIR/../..")"
fi
VERSION="${2-$(date +%Y%m%d-%H%M)}"

BUILD_ROOT="$SCRIPT_DIR/build"
BUILD_WIN="$BUILD_ROOT/win64"
STAGING="$BUILD_WIN/package-staging"
PKG_DIR="$BUILD_WIN/packages"
PKG_NAME="GrandOrgue-Win64-$VERSION.zip"
EXPORT_DIR="/media/sf_Code_Exchange/GrandOrgue Dev/packages"

mkdir -p "$STAGING" "$PKG_DIR" "$EXPORT_DIR"

echo "SRC_DIR = $SRC_DIR"
echo "BUILD_WIN = $BUILD_WIN"
echo "STAGING = $STAGING"
echo "PACKAGE OUTPUT DIR = $PKG_DIR"
echo

# 1) Baue das Release (ohne explizite Debug‑Flags)
echo "=== Build (Release) starten ==="
export LANG=C
export CXXFLAGS="-O3 -DNDEBUG"
export CFLAGS="-O3 -DNDEBUG"

pushd "$BUILD_WIN" >/dev/null

# Falls noch nicht konfiguriert, konfiguriere kurz
if [[ ! -f "CMakeCache.txt" ]]; then
  echo "cmake konfigurieren..."
  cmake "$SRC_DIR" \
    $CMAKE_MINGW_PRMS \
    $CMAKE_WIN_PRMS \
    $CMAKE_APP_PRMS \
    -DASIO_SDK_DIR=/usr/local/asio-sdk \
    -DIMPORT_EXECUTABLES=../build-tools/ImportExecutables.cmake \
    -DINSTALL_DEPEND=ON \
    -DMSYS=1 -DSTATIC=0 \
    -DRTAUDIO_USE_ASIO=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$STAGING" \
    -DGO_USE_JACK=ON "$SRC_DIR"
fi

# Build main target (nicht alle packaging/Install‑targets, um PDB/convert-Probleme zu vermeiden)
cmake --build . --config Release --target GrandOrgue -- -j"$(nproc)"

# 2) Staging: kopiere die benötigten Dateien (exe + dlls + share)
echo "=== Erstelle Staging (kopiere Dateien) ==="
rm -rf "$STAGING"/*
mkdir -p "$STAGING/bin"
mkdir -p "$STAGING/share/GrandOrgue"

# Kopiere exe + dlls aus build/win64/bin
if [[ -d "$BUILD_WIN/bin" ]]; then
  cp -v "$BUILD_WIN/bin/"*.exe "$STAGING/bin/" 2>/dev/null || true
  cp -v "$BUILD_WIN/bin/"*.dll "$STAGING/bin/" 2>/dev/null || true
  # Optional: kopiere pdbs wenn vorhanden (hier nicht gewünscht)
fi

# Kopiere share/resources (help, locale, sounds, packages, etc.)
if [[ -d "$BUILD_WIN/share/GrandOrgue" ]]; then
  cp -rv "$BUILD_WIN/share/GrandOrgue/"* "$STAGING/share/GrandOrgue/" 2>/dev/null || true
else
  # Fallback: kopiere aus source tree
  if [[ -d "$SRC_DIR/share/GrandOrgue" ]]; then
    cp -rv "$SRC_DIR/share/GrandOrgue/"* "$STAGING/share/GrandOrgue/" 2>/dev/null || true
  fi
fi

# Weitere Dateien: resources, perftests, sounds falls vorhanden
for d in resources sounds perftests help; do
  if [[ -d "$BUILD_WIN/$d" ]]; then
    mkdir -p "$STAGING/$d"
    cp -rv "$BUILD_WIN/$d/"* "$STAGING/$d/" 2>/dev/null || true
  fi
done

# 3) Erzeuge ZIP‑Paket (falls zip fehlt, versuche 7z)
echo "=== Erzeuge Paket ==="
pushd "$STAGING" >/dev/null
if command -v zip >/dev/null 2>&1; then
  zip -r "$PKG_DIR/$PKG_NAME" ./*
elif command -v 7z >/dev/null 2>&1; then
  7z a -tzip "$PKG_DIR/$PKG_NAME" ./*
else
  echo "FEHLER: kein zip oder 7z gefunden. Paket nicht erstellt."
  popd >/dev/null
  popd >/dev/null
  exit 1
fi
popd >/dev/null

# 3b) Optional: Erzeuge NSIS‑Installer (benötigt makensis)
NSIS_OUT="$PKG_DIR/GrandOrgue-Win64-${VERSION}-setup.exe"
NSIS_SCRIPT="$PKG_DIR/GrandOrgue-Win64.nsi"

echo "=== Versuche NSIS‑Installer zu erzeugen (wenn makensis installiert ist) ==="

if command -v makensis >/dev/null 2>&1; then
  echo "makensis gefunden - erzeuge NSIS Script: $NSIS_SCRIPT"

  cat > "$NSIS_SCRIPT" <<'NSI'
  ; Auto-generated NSIS script for GrandOrgue (generated by make-windows-package.sh)
  ; placeholders: @VERSION@, @NSIS_OUT@, @STAGING@
  !define PRODUCT_NAME "GrandOrgue"
  !define PRODUCT_VERSION "@VERSION@"
  !define OUTPUT_EXE "@NSIS_OUT@"
  !define INSTALL_DIR "$PROGRAMFILES\\${PRODUCT_NAME}"

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "${OUTPUT_EXE}"
InstallDir "${INSTALL_DIR}"
ShowInstDetails show

Page directory
Page instfiles
UninstPage uninstConfirm
UninstPage instfiles

Section "Install"
  SetOutPath "$INSTDIR"
  ; copy everything from package-staging directory into installer at runtime
  ; the File command below will be expanded by NSIS at compile time
  File /r "@STAGING@\\*"
  ; create uninstaller
  WriteUninstaller "$INSTDIR\\Uninstall.exe"
SectionEnd

Section "Uninstall"
  Delete "$INSTDIR\\Uninstall.exe"
  RMDir /r "$INSTDIR"
SectionEnd
NSI

  # Replace placeholders with actual values (safe with set -u)
  sed -i "s|@VERSION@|${VERSION}|g" "$NSIS_SCRIPT"
  sed -i "s|@NSIS_OUT@|${NSIS_OUT}|g" "$NSIS_SCRIPT"
  # NSIS expects Windows-style backslashes; ensure we provide a path NSIS can use.
  # Escape backslashes for sed replacement
  ESC_STAGING=$(printf '%s\n' "$STAGING" | sed 's/\\/\\\\\\\\/g')
  sed -i "s|@STAGING@|${ESC_STAGING}|g" "$NSIS_SCRIPT"

  echo "NSIS Script geschrieben. Starte makensis..."
  makensis "$NSIS_SCRIPT" || {
    echo "Warnung: makensis schlug fehl. NSIS Installer nicht erstellt."
  }
else
  echo "makensis nicht gefunden — überspringe NSIS‑Erzeugung. (Installiere 'nsis' um .exe zu erzeugen.)"
fi

# 4) Export / copy package to shared folder (if available)
if [[ -d "$EXPORT_DIR" ]]; then
  cp -v "$PKG_DIR/$PKG_NAME" "$EXPORT_DIR/" || true
  # falls NSIS erzeugt wurde, kopiere auch das .exe
  if [[ -f "$NSIS_OUT" ]]; then
    cp -v "$NSIS_OUT" "$EXPORT_DIR/" || true
  fi
fi

echo "Paket erstellt: $PKG_DIR/$PKG_NAME"
if [[ -f "$NSIS_OUT" ]]; then
  echo "NSIS Installer erstellt: $NSIS_OUT"
else
  echo "NSIS Installer nicht erstellt."
fi
echo "Optional kopiert nach: $EXPORT_DIR"

popd >/dev/null

echo "Fertig."
